### ISSUE TITLE
Encodable source data size?

### ISSUE THREAD

**Issue by zygoat** [xjunior/XRSA#1]
The encode routine appears to be of dubious value since it only seems able to encode a plaintext of about a hundred bytes in length (block size minus twelve).

**Comment by wyszo** [comment]
That's the RSA algorithm limitation (not the library fault)! Read http://stackoverflow.com/questions/5866129/rsa-encryption-problem-size-of-payload-data/5868456#5868456 and http://security.stackexchange.com/questions/44702/whats-the-limit-on-the-size-of-the-data-that-public-key-cryptos-can-handle

**Comment by xjunior** [comment]
@wyszo I'm not actively maintaining this library. I don't mind adding you as collaborator as it seem like you've been active here.

**Comment by wyszo** [comment]
@xjunior Nah, that's all right, I won't be making any more commits. Just wanted to say thanks and give back by making the small change you merged yesterday.

**Comment by xjunior** [comment]
Thanks, @wyszo
