### ISSUE TITLE
Can not read certificate from data

### ISSUE THREAD

**Issue by hdoria** [xjunior/XRSA#3]
I followed all the steps, but I keep getting the following error:

Can not read certificate from data

What I am doing wrong?

**Comment by evenluo** [comment]
@marcingravity , did .der certificate work ? Seems not working in my case.

**Comment by tadeegan** [comment]
Im working with .pem and am having the same issue

**Comment by wyszo** [comment]
It has to be x509 certificate. It works if you generate it like described in the Readme file.

**Comment by xjunior** [comment]
As explained above, the lib is designed to work with a limited types of certificates. I no longer use it, but it is open for pull requests.
