### ISSUE TITLE
SecKeyEncrypt fail with rsa:2048 public key.

### ISSUE THREAD

**Issue by jefffarkas** [xjunior/XRSA#4]
I've created a key with the following command:

`openssl req -x509 -out public_key.der -outform der -new -newkey rsa:2048 -keyout private_key.pem -days 3650`

Upon calling `[rsa encryptToString:string]`, I receive the following error:

`SecKeyEncrypt fail. Error Code: 4294967246`

**Comment by wyszo** [comment]
The library doesn't support keys longer than 2048. I've made a fix for that. See:  https://github.com/xjunior/XRSA/pull/5 (or checkout my fork: https://github.com/wyszo/XRSA/tree/feature/keylengths)

**Comment by xjunior** [comment]
#5 fixes this. Thanks @wyszo
