### ISSUE TITLE
Can I use this with a Public Key as a String?

### ISSUE THREAD

**Issue by jlubeck** [xjunior/XRSA#6]
So this is my public key:

"-----BEGIN PUBLIC KEY-----\nMIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGC4BKxhVX7BXWjhlgkuskYtsYK9\nhMf+qJUgLevsLb28XxuPsmW3tjxHO3FV8FCj1+XLXLOCMeQvFU4jvMD+nPKKVPxN\ninAiTcl0pQYUi3kHAY9M8X9PgXrGXTwHL3BiM6QNt1fMYD1yRhu8hS6w1Kg7dDgV\ns8BOQgLvm4iHRDG7AgMBAAE=\n-----END PUBLIC KEY-----"

but when I try to use it with this library I always get an error "Can not read certificate from data"

I tried converting that to base64, stripping the "-----BEGIN PUBLIC KEY-----" and \n, but nothing seems to work. Am I doing something wrong, or is this just not possible?

Thank you

**Comment by xjunior** [comment]
@jlubeck anyway you can get your key into a NSData should work. From a string, the easist way is to make your key into base64 as shown in the README

**Comment by jlubeck** [comment]
But I tried doing what it says in the readme and I'm getting the error I mentioned.

**Comment by xjunior** [comment]
This library basically wraps Apple's Security Framework in a nicer way. If you're getting this error that means that SecCertificateCreateWithData is failing to load your certificate.

**Comment by jlubeck** [comment]
I know it's not your place, and I'm definitely grateful for your project. Do you think there is any change that you can try loading my certificate on your side to see if I'm doing something wrong or the problem is somewhere else?

I understand if you can't though, it would just be really helpful to me.

Thanks again for your contribution

**Comment by xjunior** [comment]
Sorry, @jlubeck. I really wish I could. But as I'm not working on this anymore – and right now not even on iOS development, I don't have the environment set up here to try this out.

**Comment by xjunior** [comment]
I have a suggestion, though.

This seem to be your key: `MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGC4BKxhVX7BXWjhlgkuskYtsYK9\nhMf+qJUgLevsLb28XxuPsmW3tjxHO3FV8FCj1+XLXLOCMeQvFU4jvMD+nPKKVPxN\ninAiTcl0pQYUi3kHAY9M8X9PgXrGXTwHL3BiM6QNt1fMYD1yRhu8hS6w1Kg7dDgV\ns8BOQgLvm4iHRDG7AgMBAAE=`, not the whole thing you're using.
